### ISSUE TITLE
starter does not work

### ISSUE THREAD

**Issue by ghost** [oneezy/histoire-svelte#1]
why ?

Collect stories start all
Error while collecting story /Users/0-minuit-ax/0-dev/offical/hist-svelte/src/BaseButton.story.svelte:
TypeError: Cannot set property target of #<Event> which has only a getter
    at EventTarget.dispatchEvent (/Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/happy-dom@2.55.0/node_modules/happy-dom/lib/event/EventTarget.js:42:26)
    at /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/proxy.js:310:10
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/hot-api.js:3:31
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/index.js:1:238
Error while collecting story /Users/0-minuit-ax/0-dev/offical/hist-svelte/src/Meow.story.svelte:
TypeError: Cannot set property target of #<Event> which has only a getter
    at EventTarget.dispatchEvent (/Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/happy-dom@2.55.0/node_modules/happy-dom/lib/event/EventTarget.js:42:26)
    at /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/proxy.js:310:10
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/hot-api.js:3:31
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/index.js:1:238
Error while collecting story /Users/0-minuit-ax/0-dev/offical/hist-svelte/src/NoIframe.story.svelte:
TypeError: Cannot set property target of #<Event> which has only a getter
    at EventTarget.dispatchEvent (/Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/happy-dom@2.55.0/node_modules/happy-dom/lib/event/EventTarget.js:42:26)
    at /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/proxy.js:310:10
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/hot-api.js:3:31
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/index.js:1:238
Error while collecting story /Users/0-minuit-ax/0-dev/offical/hist-svelte/src/Cars.story.svelte:
TypeError: Cannot set property target of #<Event> which has only a getter
    at EventTarget.dispatchEvent (/Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/happy-dom@2.55.0/node_modules/happy-dom/lib/event/EventTarget.js:42:26)
    at /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/proxy.js:310:10
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/hot-api.js:3:31
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/index.js:1:238
Error while collecting story /Users/0-minuit-ax/0-dev/offical/hist-svelte/src/ShareControls.story.svelte:
TypeError: Cannot set property target of #<Event> which has only a getter
    at EventTarget.dispatchEvent (/Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/happy-dom@2.55.0/node_modules/happy-dom/lib/event/EventTarget.js:42:26)
    at /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/proxy.js:310:10
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/hot-api.js:3:31
    at async ViteNodeRunner.directRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:193:5)
    at async ViteNodeRunner.cachedRequest (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:89:12)
    at async request (file:///Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/vite-node@0.21.1/node_modules/vite-node/dist/client.mjs:111:21)
    at async /Users/0-minuit-ax/0-dev/offical/hist-svelte/node_modules/.pnpm/svelte-hmr@0.14.12_svelte@3.49.0/node_modules/svelte-hmr/runtime/index.js:1:238

**Comment by ghost** [comment]
another typo error in the doc: https://histoire.dev/guide/svelte3/docs.html
there is  a useless " near count: 
  <input
      bind:value={count}"
      type="number"
    >

The doc tab of Histoire does not refresh automatically, I need to restart the server to update it
This source-code sample was not working for me...
